
version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:v1.5.8 

    branches:
      only: master

    steps:
      - checkout

      - run:
          working_directory: flutter
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          working_directory: flutter
          name: Run the application tests
          command: flutter test

      - run:
          working_directory: flutter
          name: Build the Android version
          command: flutter build apk 

      - run:
          working_directory: flutter
          name: Build the Android version
          command: flutter build web 

      - store_artifacts:
          path: flutter/buld/web
